/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "akc_encrypt.h"



/* Header for class com_view_akcencrypt_api_AKCEncryptWrapper */

#ifndef _Included_com_view_akcencrypt_api_AKCEncryptWrapper
#define _Included_com_view_akcencrypt_api_AKCEncryptWrapper
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_view_akcencrypt_api_AKCEncryptWrapper
 * Method:    NativeSM3ABCTEST
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_view_akcencrypt_api_AKCEncryptWrapper_NativeSM3ABCTEST
        (JNIEnv *, jobject);

/*
 * Class:     com_view_akcencrypt_api_AKCEncryptWrapper
 * Method:    NativeSM4ABCENCRYPTTEST
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_view_akcencrypt_api_AKCEncryptWrapper_NativeSM4ABCENCRYPTTEST
        (JNIEnv *, jobject);
/*
 * Class:     com_view_akcencrypt_api_AKCEncryptWrapper
 * Method:    NativeSM4ABCDEENCRYPTTEST
 * Signature: ()[B[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_view_akcencrypt_api_AKCEncryptWrapper_NativeSM4ABCDEENCRYPTTEST
        (JNIEnv *, jobject,jbyteArray);

/*
 * Class:     com_view_akcencrypt_api_AKCEncryptWrapper
 * Method:    NativeGeneratekeyPair
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_view_akcencrypt_api_AKCEncryptWrapper_NativeGeneratekeyPair
  (JNIEnv *, jobject);

/*
 * Class:     com_view_akcencrypt_api_AKCEncryptWrapper
 * Method:    NativeSenderRootKey
 * Signature: ([B[B[B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_view_akcencrypt_api_AKCEncryptWrapper_NativeSenderRootKey
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_view_akcencrypt_api_AKCEncryptWrapper
 * Method:    NativeReceiverRootKey
 * Signature: ([B[B[B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_view_akcencrypt_api_AKCEncryptWrapper_NativeReceiverRootKey
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_view_akcencrypt_api_AKCEncryptWrapper
 * Method:    NativeChainKey
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_view_akcencrypt_api_AKCEncryptWrapper_NativeChainKey
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_view_akcencrypt_api_AKCEncryptWrapper
 * Method:    NativeChainKeyNext
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_view_akcencrypt_api_AKCEncryptWrapper_NativeChainKeyNext
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_view_akcencrypt_api_AKCEncryptWrapper
 * Method:    NativeMessageHeadKey
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_view_akcencrypt_api_AKCEncryptWrapper_NativeMessageHeadKey
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_view_akcencrypt_api_AKCEncryptWrapper
 * Method:    NativeMessageMF
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_view_akcencrypt_api_AKCEncryptWrapper_NativeMessageMF
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_view_akcencrypt_api_AKCEncryptWrapper
 * Method:    NativeMessageHMAC
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_view_akcencrypt_api_AKCEncryptWrapper_NativeMessageHMAC
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_view_akcencrypt_api_AKCEncryptWrapper
 * Method:    NativeMessageKeyAndIVAndMac
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_view_akcencrypt_api_AKCEncryptWrapper_NativeMessageKeyAndIVAndMac
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_view_akcencrypt_api_AKCEncryptWrapper
 * Method:    NativeSignature
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_view_akcencrypt_api_AKCEncryptWrapper_NativeSignature
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_view_akcencrypt_api_AKCEncryptWrapper
 * Method:    NativeVerifySignature
 * Signature: ([B[B[B)I
 */
JNIEXPORT jint JNICALL Java_com_view_akcencrypt_api_AKCEncryptWrapper_NativeVerifySignature
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_view_akcencrypt_api_AKCEncryptWrapper
 * Method:    NativeEncryptData
 * Signature: ([BJ[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_view_akcencrypt_api_AKCEncryptWrapper_NativeEncryptData
  (JNIEnv *, jobject, jbyteArray, jlong, jbyteArray, jbyteArray);

/*
 * Class:     com_view_akcencrypt_api_AKCEncryptWrapper
 * Method:    NativeDecryptData
 * Signature: ([BJ[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_view_akcencrypt_api_AKCEncryptWrapper_NativeDecryptData
  (JNIEnv *, jobject, jbyteArray, jlong, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
